export const LOCATION_SOURCES = Object.freeze({
  BACKGROUND: 'BACKGROUND',
  CHECKIN: 'CHECKIN',
  CHECKOUT: 'CHECKOUT',
  MANUAL: 'MANUAL',
  LIVE_REFRESH: 'LIVE_REFRESH',
});

export const PERSISTENT_LOCATION_SOURCES = [
  LOCATION_SOURCES.BACKGROUND,
  LOCATION_SOURCES.CHECKIN,
  LOCATION_SOURCES.CHECKOUT,
  LOCATION_SOURCES.MANUAL,
];

export const LIVE_ONLY_LOCATION_SOURCES = [
  LOCATION_SOURCES.LIVE_REFRESH,
];
